### ISSUE TITLE
Lazy Loading Routes

### ISSUE THREAD

**Issue by ashishjaink** [bleenco/angular-webpack-seed#2]
Hi @jkuri @irmana , with the new upgrade in the seed from v4 => v5 you guys removed the lazy loading route, was it intentional and does v5 not support it?

**Comment by jkuri** [comment]
hi @ashishjaink. it was definitely not removed intentionaly, I will check on it and let you know.

**Comment by ashishjaink** [comment]
Sure thanks, as i had tried it but i was getting SourceMap issues while compilation.

**Comment by malikov917** [comment]
@ashishjaink hi, I've just resolved this issue. I'll make pull request

**Comment by jkuri** [comment]
merged. closing this issue.
